// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3g-A--yCMAFGI-UNdWQjPh9P9Ov_x9vk',
    appId: '1:825934214057:android:9397273dd51b806abd4ab8',
    messagingSenderId: '825934214057',
    projectId: 'flutter-fcm-cef6b',
    storageBucket: 'flutter-fcm-cef6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAznNfJpOnok4o7UfSVHjqgkU5Izy9R8lA',
    appId: '1:825934214057:ios:c91366949c6a4f00bd4ab8',
    messagingSenderId: '825934214057',
    projectId: 'flutter-fcm-cef6b',
    storageBucket: 'flutter-fcm-cef6b.appspot.com',
    iosClientId: '825934214057-cutevrd21rcbfe33d3he9sb23up5t410.apps.googleusercontent.com',
    iosBundleId: 'com.example.fcm',
  );
}
